config/routes.rb
Rails.application.routes.draw do
  get 'new_layout/index'
  get 'news/index'
  root 'home#index'
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/new_layout_controller.rb
class NewLayoutController < ApplicationController
  layout 'new_layout'
  def index
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/new_layout_helper.rb
module NewLayoutHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml
%p=link_to 'news_index', news_index_path
%p=link_to 'home_index', home_index_path
%p=link_to 'new_layout_index', new_layout_index_path
%p 静的イメージはpulicフォルダーに置く↓　%img{src: "images/thumbnail_IMG_1887.jpg", height: "80", width: "100"}
%img{src: "images/thumbnail_IMG_1887.jpg", height: "80", width: "100"}
%p image_tagを利用する場合はassets/imagesに置く↓= image_tag "google/googlelogo_color_272x92dp.png", height: "80", width: "100"
= image_tag "google/googlelogo_color_272x92dp.png", height: "80", width: "100"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TciCnWebsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag    "#{controller_name}/style", media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "#{controller_name}/javascript", 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <p>This is app/views/layouts/application.html.erb</p>
    <%= yield %>
  </body>
</html>

app/views/layouts/new_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TciCnWebsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <p>This is app/views/layouts/new_layout.html.erb</p>
    <%= yield %>
  </body>
</html>

app/views/new_layout/index.html.haml
%h1 NewLayout#index
%p Find me in app/views/new_layout/index.html.haml

app/views/news/index.html.haml
%h1 News#index
%p Find me in app/views/news/index.html.haml